### ISSUE TITLE
Score toekennen gaat verkeerd door dichtbijzijnste 

### ISSUE THREAD

**Issue by Labhatorian** [KBSB4/VirtualPiano#28]
Ook al is noot gespeeld, hij pakt hem nog steeds.

Zet PressedDown op true en benoem deze issue #28 in de commit + pullrequest

**Comment by jaelkwakkel** [comment]
Fixed in commit: https://github.com/KBSB4/VirtualPiano/commit/d1bcea75eb6fb7be6fcce54b573c758c9dc9a6b4
